version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: file_parser_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - file_parser_network

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: file_parser_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - file_parser_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - file_parser_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=file_parser.settings
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - file_parser_network

volumes:
  postgres_data:
  mongodb_data:


networks:
  file_parser_network:
    driver: bridge
